package com.mycompany.mapita.modelo;
// Generated 08-feb-2019 14:35:07 by Hibernate Tools 4.3.1



/**
 * Marcador generated by hbm2java
 */
public class Marcador  implements java.io.Serializable {


     private int idmarcador;
     private Usuario usuario;
     private Float latitud;
     private Float longitud;
     private String descripcion;

    public Marcador() {
    }

	
    public Marcador(int idmarcador) {
        this.idmarcador = idmarcador;
    }
    public Marcador(int idmarcador, Usuario usuario, Float latitud, Float longitud, String descripcion) {
       this.idmarcador = idmarcador;
       this.usuario = usuario;
       this.latitud = latitud;
       this.longitud = longitud;
       this.descripcion = descripcion;
    }
   
    public int getIdmarcador() {
        return this.idmarcador;
    }
    
    public void setIdmarcador(int idmarcador) {
        this.idmarcador = idmarcador;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Float getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(Float latitud) {
        this.latitud = latitud;
    }
    public Float getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(Float longitud) {
        this.longitud = longitud;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


